<?php
include_once __DIR__ . "/../components/shared/preloader.shared.php";
include_once __DIR__ . "/../components/layouts/top-layout.layout.php";
include_once __DIR__ . "/../components/shared/datanotfound.shared.php";
?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <li>
        <h1>Read Carefully</h1>
                <p>These are the terms and conditions of service, which apply to the use of the website (www.amazingstakes.com referred as Amazingstakes  | Amazing Stakes) by you (the users). By accessing www.amazingstakes.com, you agree to be bound by these Terms and Conditions and our Privacy Policy and are deemed to have accepted and understood all the Conditions.</p>
                <p>
                    These Conditions apply to any and all who use this website. By accessing and using this website you agree to be bound by these Terms of Use. We reserve the right to update or amend these Terms of Use at any time. We may make alterations to these Terms of Use from time to time and these variations shall become effective immediately upon being accessible from this website. Everyone has to become familiar with the terms before using the resources of the site.
                </p>
                <h2>Service</h2>
                <p>All visitors to our site are considered users of the services of the website. The services of this website are expressed in the publishing of information on football matches such as predictions, tips, statistics, past results, and fixtures. The predictions are generated by a complex and unique mathematical algorithm based on statistical football data which are then presented to the users.</p>
<p>All football predictions provided by amazingstakes are for information purposes and each user uses the information from this site at his sole reasonable discretion. We work to verify the accuracy of any information we place on www.amazingstakes.com, but we make no warranties, whether express or implied in relation to its accuracy. Your use of the Website is at your sole risk. The predictions made represent the views of amazingstakes only.</p>
<p> You acknowledge that we shall have no liability of any kind whatsoever arising out of any decisions that you make as a result of viewing the Website. We are not responsible if information made available on this site is not accurate, complete or current. The material on this site is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or more timely sources of information. Any reliance on the material on this site is at your own sole discretion. As part of our commitment, amazingstakes is committed to supporting responsible gambling. We advise that all users must be 18+.</p>
                                        </li>
                    </ul>
            </P>
            <p>Amazing Stakes is the solution to excessive losses for soccer punters and the confidence into sports investment.</p>
            <br/>
        </div>
    </div>
</div>

<?php

include_once __DIR__ . "/../components/layouts/bottom-layout.layout.php";
